### ISSUE TITLE
convert value multitime on peeking

### ISSUE THREAD

**Issue by MegdadFadaee** [mziraki/nova-persian-date-field#3]
hello sir.
when used field, in peeking request the value is converted several times and finally it becomes "invalid date".

https://github.com/user-attachments/assets/8b930ec0-dca1-43f1-8ce7-46c35520cf8d

**Comment by mziraki** [comment]
Hi,
this package is for personal use and I don't need peeking feature of Nova, feel free to fork the repo and patch it.
